"""create storytellers

Revision ID: 1785ebcbebea
Revises: 3c1c81d1cfd6
Create Date: 2026-09-12 18:47:42.817247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1785ebcbebea'
down_revision: Union[str, Sequence[str], None] = '3c1c81d1cfd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storytellers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('portrait_url', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storytellers_created_at'), 'storytellers', ['created_at'], unique=False)
    op.create_index(op.f('ix_storytellers_id'), 'storytellers', ['id'], unique=False)
    op.create_index(op.f('ix_storytellers_name'), 'storytellers', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storytellers_name'), table_name='storytellers')
    op.drop_index(op.f('ix_storytellers_id'), table_name='storytellers')
    op.drop_index(op.f('ix_storytellers_created_at'), table_name='storytellers')
    op.drop_table('storytellers')
    # ### end Alembic commands ###
