"""align_stories_schema

Revision ID: 2742d1b551e8
Revises: c5e8210f9831
Create Date: 2026-09-22 23:12:36.455809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2742d1b551e8'
down_revision: Union[str, Sequence[str], None] = 'c5e8210f9831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapters',
    sa.Column('story_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('preview_available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'order', name='uq_chapter_story_order')
    )
    op.create_index(op.f('ix_chapters_created_at'), 'chapters', ['created_at'], unique=False)
    op.create_index(op.f('ix_chapters_id'), 'chapters', ['id'], unique=False)
    op.create_index(op.f('ix_chapters_order'), 'chapters', ['order'], unique=False)
    op.create_index(op.f('ix_chapters_story_id'), 'chapters', ['story_id'], unique=False)
    op.create_table('story_categories',
    sa.Column('story_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('story_id', 'category_id')
    )
    op.create_index(op.f('ix_story_categories_category_id'), 'story_categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_story_categories_story_id'), 'story_categories', ['story_id'], unique=False)
    op.create_table('story_languages',
    sa.Column('story_id', sa.String(length=36), nullable=False),
    sa.Column('language_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('story_id', 'language_id')
    )
    op.create_index(op.f('ix_story_languages_language_id'), 'story_languages', ['language_id'], unique=False)
    op.create_index(op.f('ix_story_languages_story_id'), 'story_languages', ['story_id'], unique=False)
    op.create_table('audio_assets',
    sa.Column('story_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('access_type', sa.Enum('PUBLIC_PREVIEW', 'PROTECTED', name='audioaccesstype', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_assets_access_type'), 'audio_assets', ['access_type'], unique=False)
    op.create_index(op.f('ix_audio_assets_chapter_id'), 'audio_assets', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_audio_assets_created_at'), 'audio_assets', ['created_at'], unique=False)
    op.create_index(op.f('ix_audio_assets_id'), 'audio_assets', ['id'], unique=False)
    op.create_index(op.f('ix_audio_assets_storage_key'), 'audio_assets', ['storage_key'], unique=False)
    op.create_index(op.f('ix_audio_assets_story_id'), 'audio_assets', ['story_id'], unique=False)
    op.create_table('listening_progress',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('story_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('position_seconds', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'story_id', 'chapter_id', name='uq_user_story_chapter_progress')
    )
    op.create_index(op.f('ix_listening_progress_chapter_id'), 'listening_progress', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_listening_progress_created_at'), 'listening_progress', ['created_at'], unique=False)
    op.create_index(op.f('ix_listening_progress_id'), 'listening_progress', ['id'], unique=False)
    op.create_index(op.f('ix_listening_progress_is_completed'), 'listening_progress', ['is_completed'], unique=False)
    op.create_index(op.f('ix_listening_progress_story_id'), 'listening_progress', ['story_id'], unique=False)
    op.create_index(op.f('ix_listening_progress_user_id'), 'listening_progress', ['user_id'], unique=False)
    op.add_column('categories', sa.Column('slug', sa.String(length=120), nullable=False))
    op.add_column('categories', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.drop_constraint(op.f('uq_events_slug'), 'events', type_='unique')
    op.drop_constraint(op.f('uq_journal_articles_slug'), 'journal_articles', type_='unique')
    op.add_column('languages', sa.Column('native_name', sa.String(length=100), nullable=True))
    op.add_column('languages', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('languages', 'code',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.drop_index(op.f('ix_languages_name'), table_name='languages')
    op.create_index(op.f('ix_languages_is_active'), 'languages', ['is_active'], unique=False)
    op.drop_column('languages', 'description')
    op.drop_constraint(op.f('products_slug_key'), 'products', type_='unique')
    op.add_column('stories', sa.Column('slug', sa.String(length=255), nullable=False))
    op.add_column('stories', sa.Column('short_description', sa.Text(), nullable=True))
    op.add_column('stories', sa.Column('long_description', sa.Text(), nullable=True))
    op.add_column('stories', sa.Column('cover_image', sa.String(length=1024), nullable=True))
    op.add_column('stories', sa.Column('hero_media', sa.String(length=1024), nullable=True))
    op.add_column('stories', sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'PUBLISHED', 'ARCHIVED', name='storystatus', native_enum=False, length=32), nullable=False))
    op.add_column('stories', sa.Column('themes', sa.JSON(), nullable=False))
    op.add_column('stories', sa.Column('narrator', sa.String(length=255), nullable=True))
    op.add_column('stories', sa.Column('age_group', sa.String(length=64), nullable=True))
    op.add_column('stories', sa.Column('cultural_context', sa.Text(), nullable=True))
    op.add_column('stories', sa.Column('transcript', sa.Text(), nullable=True))
    op.add_column('stories', sa.Column('product_id', sa.String(length=64), nullable=True))
    op.add_column('stories', sa.Column('featured', sa.Boolean(), nullable=False))
    op.add_column('stories', sa.Column('seo_title', sa.String(length=255), nullable=True))
    op.add_column('stories', sa.Column('seo_description', sa.String(length=500), nullable=True))
    op.alter_column('stories', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_stories_category_id'), table_name='stories')
    op.drop_index(op.f('ix_stories_language_id'), table_name='stories')
    op.drop_index(op.f('ix_stories_region_id'), table_name='stories')
    op.drop_index(op.f('ix_stories_storyteller_id'), table_name='stories')
    op.drop_index(op.f('ix_stories_title'), table_name='stories')
    op.create_index(op.f('ix_stories_featured'), 'stories', ['featured'], unique=False)
    op.create_index(op.f('ix_stories_product_id'), 'stories', ['product_id'], unique=False)
    op.create_index(op.f('ix_stories_slug'), 'stories', ['slug'], unique=True)
    op.create_index(op.f('ix_stories_status'), 'stories', ['status'], unique=False)
    op.drop_constraint(op.f('stories_language_id_fkey'), 'stories', type_='foreignkey')
    op.drop_constraint(op.f('stories_region_id_fkey'), 'stories', type_='foreignkey')
    op.drop_constraint(op.f('stories_storyteller_id_fkey'), 'stories', type_='foreignkey')
    op.drop_constraint(op.f('stories_category_id_fkey'), 'stories', type_='foreignkey')
    op.drop_column('stories', 'region_id')
    op.drop_column('stories', 'category_id')
    op.drop_column('stories', 'content')
    op.drop_column('stories', 'language_id')
    op.drop_column('stories', 'audio_available')
    op.drop_column('stories', 'storyteller_id')
    op.drop_column('stories', 'publication_date')
    op.drop_column('stories', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('stories', sa.Column('publication_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('stories', sa.Column('storyteller_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.add_column('stories', sa.Column('audio_available', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('stories', sa.Column('language_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.add_column('stories', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('stories', sa.Column('category_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.add_column('stories', sa.Column('region_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('stories_category_id_fkey'), 'stories', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(op.f('stories_storyteller_id_fkey'), 'stories', 'storytellers', ['storyteller_id'], ['id'])
    op.create_foreign_key(op.f('stories_region_id_fkey'), 'stories', 'regions', ['region_id'], ['id'])
    op.create_foreign_key(op.f('stories_language_id_fkey'), 'stories', 'languages', ['language_id'], ['id'])
    op.drop_index(op.f('ix_stories_status'), table_name='stories')
    op.drop_index(op.f('ix_stories_slug'), table_name='stories')
    op.drop_index(op.f('ix_stories_product_id'), table_name='stories')
    op.drop_index(op.f('ix_stories_featured'), table_name='stories')
    op.create_index(op.f('ix_stories_title'), 'stories', ['title'], unique=False)
    op.create_index(op.f('ix_stories_storyteller_id'), 'stories', ['storyteller_id'], unique=False)
    op.create_index(op.f('ix_stories_region_id'), 'stories', ['region_id'], unique=False)
    op.create_index(op.f('ix_stories_language_id'), 'stories', ['language_id'], unique=False)
    op.create_index(op.f('ix_stories_category_id'), 'stories', ['category_id'], unique=False)
    op.alter_column('stories', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('stories', 'seo_description')
    op.drop_column('stories', 'seo_title')
    op.drop_column('stories', 'featured')
    op.drop_column('stories', 'product_id')
    op.drop_column('stories', 'transcript')
    op.drop_column('stories', 'cultural_context')
    op.drop_column('stories', 'age_group')
    op.drop_column('stories', 'narrator')
    op.drop_column('stories', 'themes')
    op.drop_column('stories', 'status')
    op.drop_column('stories', 'hero_media')
    op.drop_column('stories', 'cover_image')
    op.drop_column('stories', 'long_description')
    op.drop_column('stories', 'short_description')
    op.drop_column('stories', 'slug')
    op.create_unique_constraint(op.f('products_slug_key'), 'products', ['slug'], postgresql_nulls_not_distinct=False)
    op.add_column('languages', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_languages_is_active'), table_name='languages')
    op.create_index(op.f('ix_languages_name'), 'languages', ['name'], unique=True)
    op.alter_column('languages', 'code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.drop_column('languages', 'is_active')
    op.drop_column('languages', 'native_name')
    op.create_unique_constraint(op.f('uq_journal_articles_slug'), 'journal_articles', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_events_slug'), 'events', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    op.alter_column('categories', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.drop_column('categories', 'is_active')
    op.drop_column('categories', 'slug')
    op.drop_index(op.f('ix_listening_progress_user_id'), table_name='listening_progress')
    op.drop_index(op.f('ix_listening_progress_story_id'), table_name='listening_progress')
    op.drop_index(op.f('ix_listening_progress_is_completed'), table_name='listening_progress')
    op.drop_index(op.f('ix_listening_progress_id'), table_name='listening_progress')
    op.drop_index(op.f('ix_listening_progress_created_at'), table_name='listening_progress')
    op.drop_index(op.f('ix_listening_progress_chapter_id'), table_name='listening_progress')
    op.drop_table('listening_progress')
    op.drop_index(op.f('ix_audio_assets_story_id'), table_name='audio_assets')
    op.drop_index(op.f('ix_audio_assets_storage_key'), table_name='audio_assets')
    op.drop_index(op.f('ix_audio_assets_id'), table_name='audio_assets')
    op.drop_index(op.f('ix_audio_assets_created_at'), table_name='audio_assets')
    op.drop_index(op.f('ix_audio_assets_chapter_id'), table_name='audio_assets')
    op.drop_index(op.f('ix_audio_assets_access_type'), table_name='audio_assets')
    op.drop_table('audio_assets')
    op.drop_index(op.f('ix_story_languages_story_id'), table_name='story_languages')
    op.drop_index(op.f('ix_story_languages_language_id'), table_name='story_languages')
    op.drop_table('story_languages')
    op.drop_index(op.f('ix_story_categories_story_id'), table_name='story_categories')
    op.drop_index(op.f('ix_story_categories_category_id'), table_name='story_categories')
    op.drop_table('story_categories')
    op.drop_index(op.f('ix_chapters_story_id'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_order'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_id'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_created_at'), table_name='chapters')
    op.drop_table('chapters')
    # ### end Alembic commands ###
